nginx:
  image: nginx
  volumes:
   - ./:/var/www
   - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
  ports:
   - 8080:80
  environment:
   - NGINX_HOST=localhost
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  links:
    - php
php:
    image: php:7-fpm
    volumes:
        - ./:/var/www


